name: pages-build-deployment

on:
   push:
     branches: [ main ]

concurrency:
  group: deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install Jekyll
      run: |
        sudo gem install bundler jekyll
        sudo bundle install

    - uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: JEKYLL_ENV=production jekyll build

    - name: Deploy
      run: |
        cd _site
        git init
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "Deploy with ${GITHUB_WORKFLOW}"
        git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages
